version: "3.9"
services:
  db:
    image: postgres:14
    container_name: fxecommerce
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres




